name: CD Pipeline (Deploy to AWS - Manual)

# Hanya jalan kalau kita klik tombol "Run workflow" di GitHub
on:
  workflow_dispatch:   # ‚Üê INI YANG BIKIN MANUAL!

permissions:
  contents: read

jobs:
  deploy:
    name: Terraform Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # v4 lebih baru & stabil

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (preview dulu)
        run: terraform plan -no-color

      - name: Terraform Apply (hanya kalau kita yakin)
        run: terraform apply -auto-approve